const ADD_TODO = 'ADD_TODO'
const CHANGE_STATUS = 'CHANGE_STATUS'
const FILTER_TODOS = 'FILTER_TODOS'
const DELETE_TODO = 'DELETE_TODO'
const UPDATE_TODO = 'UPDATE_TODO'

export { ADD_TODO, CHANGE_STATUS, FILTER_TODOS, DELETE_TODO, UPDATE_TODO }
